name: CI

on:
  push:
    branches: [ master ]
    
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: action/checkout@v2
      
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
      - name: Install Dependecies
        run: yarn
        
      - name: Build
        run: yarn build
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "., !node_modules"
          target: "test"
            
